### ISSUE TITLE
It only tracks list-like collections

### ISSUE THREAD

**Issue by mfidemraizer** [joelweiss/ChangeTracking#10]
I'm already working on a pull request to give you a possible implementation to support also `ISet<T>` implementations as a supported trackable collection. 

Are you already working on this or do you plan to do it yourself? 

In my case, I'll have to workaround modifying your library directly to support `ISet<T>`. I guess that tomorrow I'll be ready to share my implementation.

**Comment by mfidemraizer** [comment]
Well, after spending many hours on this, I've arrived to the conclusion that your library is very very tied to `List<T>` and `IBindingList`. 

I believe that a complete refactor should be needed to track any `ICollection<T>` as not everyone wants data-binding related interface implementations. In my case, I would prefer to just have generic POCO change tracking for other purposes... 

Let me know if you think that you can implement change tracking to any `ICollection<T>` implementation...

**Comment by joelweiss** [comment]
Let me know if the latest version solves your problem.

**Comment by mfidemraizer** [comment]
I'll take a look this thursday. Thank you for your effort in advance.

BTW, is your new code covering collection properties too?

**Comment by mfidemraizer** [comment]
I was going to try it, but I believe that your change won't fit well in my case. I need to still work with sets instead of lists. I mean, if you change a set to list internally, I'll lose what I get using a `HashSet<T>`.

Am I mistaken?

**Comment by joelweiss** [comment]
Sadly your not, the library internally uses `BindingList<T>` for the collection tracking so using for an internal collection something that does not implement `IList` will require a complete rewrite.

By the way you metioned
> as not everyone wants data-binding related interface implementations. In my case, I would prefer to just have generic POCO change tracking for other purposes

FYI I never used it for databinding, I also just use it for POCO tracking, I just used the build in functionality of the `BindingList<T>`.

**Comment by mfidemraizer** [comment]
Finally I decided to implement object change tracking my own way. You can take a look at the project site: http://mfidemraizer.github.io/trackerdog

It works like your implementation but if you check the docs you'll find that I could solve the issue in a more flexible way to support any collection type and there're also other improvements.

BTW I appreciate your effort and your project have been a good inspiration! You can criticize it and I'll try to improve even more! 

Thank you very much

**Comment by joelweiss** [comment]
@mfidemraizer Nice.
