### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by chrisklepeis** [joelweiss/ChangeTracking#15]
It would be helpful if there was a way to set the default value for makeComplexPropertiesTrackable and makeCollectionPropertiesTrackable globally.

**Comment by joelweiss** [comment]
Not a bad idea, I will look into it when I Have a chance.

**Comment by joelweiss** [comment]
You can change the default by setting 
```csharp
ChangeTrackingFactory.Default.MakeCollectionPropertiesTrackable = false;

ChangeTrackingFactory.Default.MakeComplexPropertiesTrackable = false;
```
