### ISSUE TITLE
Json serializing __interceptor properties

### ISSUE THREAD

**Issue by wocar** [joelweiss/ChangeTracking#16]
Hello, I love this proyect... makes things easier 🥇 
The problem now is that when I try to serialize the proxy object it serializes the __interceptor attributes example: 

```
"__interceptors": [
    {
      "$id": "3",
      "IsInitialized": true
    },
    {
      "$id": "4",
      "IsInitialized": true
    },
    {
      "$id": "5",
      "IsInitialized": true
    },
    {
      "$id": "6",
      "IsInitialized": true
    },
    {
      "$id": "7",
      "IsInitialized": true
    }
  ],
```

How can I either stop json from serializing this extra properties OR access the target object to serialize it. Thanks 👍

**Comment by wocar** [comment]
The answer would be to cast the object to IChangeTrackable and use GetOriginal().
Could we add this to the documentation? Thanks 💯

**Comment by joelweiss** [comment]
the __interceptors field is created by [Dynamic Proxy](http://www.castleproject.org/projects/dynamicproxy/) so I am not in charge of that.

However to get a non-proxied object with the non-accepted changes is currently not supported, but if you are only using simple classes meaning no complex or collection properties or you don't track them
```csharp
var trackable = order.AsTrackable(makeComplexPropertiesTrackable: false, makeCollectionPropertiesTrackable: false);
```
you could use [AutoMapper](https://github.com/AutoMapper/AutoMapper) to get a (Shallow) copy of the class and then serialize it.

Hope this helps

**Comment by wocar** [comment]
Thanks for your fast reply, might be good to have a method to support this
scenario. I serialize the object then submit it to a rest service to save
it. Guess I'm sticking to call AcceptChanges first and then
.GetOriginalValue() for the meantime

Anyways, thank you! Great project :)

**Comment by mayphi** [comment]
We had the same problem, so we added a pendant to "GetOriginal" => ["GetCurrent"](https://github.com/joelweiss/ChangeTracking/pull/25/files#diff-81e9ccdf1e7381abc9270f3ff7e05f20R254) in order to get a version of the object tree that is unproxied, so it can be serialized without having to call "AcceptChanges" and thus not being able to revert.
