### ISSUE TITLE
Add strong-name signing

### ISSUE THREAD

**Issue by RichardSinden** [joelweiss/ChangeTracking#17]
Great project, but is there a chance you could strong-name sign it, please? 
I currently can't add it into my strong-named project without manually signing it myself, which is a bit of a nuisance every time I upgrade. 
Thanks.

**Comment by joelweiss** [comment]
Strong naming just makes life difficult especially for open source projects (see [Jeremy Miller's Blog](https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds)), so I don't want to release a signed version.

Check out [Strong Namer](https://github.com/dsplaisted/strongnamer), that should make life easier for you.

HTH
