### ISSUE TITLE
Is it possible to ignore certain properties?

### ISSUE THREAD

**Issue by f135ta** [joelweiss/ChangeTracking#18]
I might be missing something really simple, but I cant see any way to exclude certain properties from being tracked. Is it possible?

**Comment by joelweiss** [comment]
No

**Comment by f135ta** [comment]
To the point.. Thanks!

**Comment by f135ta** [comment]
I've solved this..

**Comment by mattbrailsford** [comment]
@f135ta how did you solve this?

@joelweiss maybe it could be possible to pass a flag so as not to throw an exception if a property isn't virtual and thus, to ignore a property, you could just not make it virtual?

**Comment by joelweiss** [comment]
@mattbrailsford Fair idea, will keep it in mind
