### ISSUE TITLE
Configurability

### ISSUE THREAD

**Issue by weitzhandler** [joelweiss/ChangeTracking#20]
Hello and thanks for this great project.

It would be nice to have a non-static version of this library exposed as interface (i.e. `IChangeTrackingFactory`) that exposes the `AsTrackable`, `CastToIChangeTrackable`, `CastToIChangeTrackableCollection` etc. methods.

This would enable control over the generated proxy, adding additional interceptors and some more.
Besides, it would then be allow DI of a pre-configured proxy-factory singleton via the IoC container in MVC or MVVM scenarios.

**Comment by joelweiss** [comment]
Added 
```csharp
public class ChangeTrackingFactory : IChangeTrackingFactory
```
where you can configure `MakeComplexPropertiesTrackable` and `makeCollectionPropertiesTrackable`

for other scenarios you would like to enable, please open a separate issue.
