### ISSUE TITLE
.Net standard support

### ISSUE THREAD

**Issue by johnamcruz** [joelweiss/ChangeTracking#22]
Is there going to be .net standard support for this library? I would love to use it on a xamarin project.

**Comment by joelweiss** [comment]
Short answer: Yes.

Long answer: I started porting it a while back, but there were a lot of changes since a lot of the api was not available in netstandard 1.x, so I decided to wait for netstandard 2.0 (which was released at build last week as a preview), so will do a port soonish.

**Comment by johnamcruz** [comment]
is there an ETA for that @joelweiss?

**Comment by joelweiss** [comment]
I started the port [here](https://github.com/joelweiss/ChangeTracking/tree/netstandard), but xamarin wont have support for 2.0 untill vNext see [.NET Standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)

**Comment by johnamcruz** [comment]
@joelweiss i tihnk it can be ported to .NET standard 1.3 at the minimum. Castle Core supports .NET Standard 1.3. Are there other dependencies?

**Comment by joelweiss** [comment]
It would require significant changes, see [ApiPort](https://github.com/Microsoft/dotnet-apiport) report below.

| Target member                                                                                                                                           | .NET Standard   | Recommended changes                                                                                    |
|---------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------|--------------------------------------------------------------------------------------------------------|
| T:System.Runtime.CompilerServices.CallSite`1                                                                                                            | Supported: 2.0+ |                                                                                                        |
| T:System.ComponentModel.AddingNewEventArgs                                                                                                              | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.AddingNewEventArgs.#ctor(System.Object)                                                                                         | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.AddingNewEventArgs.get_NewObject                                                                                                | Supported: 2.0+ |                                                                                                        |
| T:System.ComponentModel.IBindingList                                                                                                                    | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IBindingList.add_ListChanged(System.ComponentModel.ListChangedEventHandler)                                                     | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IBindingList.remove_ListChanged(System.ComponentModel.ListChangedEventHandler)                                                  | Supported: 2.0+ |                                                                                                        |
| T:System.ComponentModel.IChangeTracking                                                                                                                 | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IChangeTracking.AcceptChanges                                                                                                   | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IChangeTracking.get_IsChanged                                                                                                   | Supported: 2.0+ |                                                                                                        |
| T:System.ComponentModel.IRevertibleChangeTracking                                                                                                       | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IRevertibleChangeTracking.RejectChanges                                                                                         | Supported: 2.0+ |                                                                                                        |
| T:System.ComponentModel.ICancelAddNew                                                                                                                   | Supported: 2.0+ |                                                                                                        |
| T:Microsoft.CSharp.RuntimeBinder.CSharpBinderFlags                                                                                                      | Not supported   |                                                                                                        |
| T:System.ComponentModel.IEditableObject                                                                                                                 | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IEditableObject.BeginEdit                                                                                                       | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IEditableObject.CancelEdit                                                                                                      | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.IEditableObject.EndEdit                                                                                                         | Supported: 2.0+ |                                                                                                        |
| T:System.ComponentModel.ListChangedEventHandler                                                                                                         | Supported: 2.0+ |                                                                                                        |
| M:System.ComponentModel.ListChangedEventHandler.#ctor(System.Object,System.IntPtr)                                                                      | Supported: 2.0+ |                                                                                                        |
| T:Microsoft.CSharp.RuntimeBinder.Binder                                                                                                                 | Not supported   |                                                                                                        |
| M:Microsoft.CSharp.RuntimeBinder.Binder.InvokeMember…….                                                                                                 | Not supported   |                                                                                                        |
| T:System.Runtime.CompilerServices.CallSiteBinder                                                                                                        | Supported: 2.0+ |                                                                                                        |
| T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfoFlags                                                                                                | Not supported   |                                                                                                        |
| T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo                                                                                                     | Not supported   |                                                                                                        |
| M:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create(Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfoFlags,System.String)                        | Not supported   |                                                                                                        |
| T:System.ComponentModel.ListChangedEventArgs                                                                                                            | Supported: 2.0+ |                                                                                                        |
| T:System.ComponentModel.BindingList`1                                                                                                                   | Supported: 2.0+ |                                                                                                        |
| T:System.Runtime.CompilerServices.CallSite                                                                                                              | Supported: 2.0+ |                                                                                                        |
| T:System.Reflection.Binder                                                                                                                              | Supported: 2.0+ | Use an overload that does not take a Binder.                                                           |
| M:System.Type.get_BaseType                                                                                                                              | Supported: 2.0+ | .GetTypeInfo().BaseType.                                                                               |
| M:System.Type.get_IsClass                                                                                                                               | Supported: 2.0+ | .GetTypeInfo().IsClass.                                                                                |
| M:System.Type.get_IsInterface                                                                                                                           | Supported: 2.0+ | .GetTypeInfo().IsInterface.                                                                            |
| M:System.Type.get_IsSealed                                                                                                                              | Supported: 2.0+ | .GetTypeInfo().IsSealed.                                                                               |
| M:System.Type.GetConstructor(System.Type[])                                                                                                             | Not supported   |                                                                                                        |
| M:System.Type.GetField(System.String,System.Reflection.BindingFlags)                                                                                    | Not supported   |                                                                                                        |
| M:System.Type.GetGenericArguments                                                                                                                       | Not supported   |                                                                                                        |
| M:System.Type.GetInterface(System.String)                                                                                                               | Supported: 2.0+ | Use typeof(TypeYoureInterestedIn).GetTypeInfo().GetInterface(System.String).                           |
| M:System.Type.GetInterfaceMap(System.Type)                                                                                                              | Supported: 2.0+ |                                                                                                        |
| M:System.Type.GetInterfaces                                                                                                                             | Not supported   |                                                                                                        |
| M:System.Type.GetMethod(System.String,System.Reflection.BindingFlags)                                                                                   | Not supported   | Equivalent available: Add using for System.Reflection, and reference System.Reflection.TypeExtensions. |
| M:System.Type.GetMethods(System.Reflection.BindingFlags)                                                                                                | Not supported   |                                                                                                        |
| M:System.Type.GetProperties(System.Reflection.BindingFlags)                                                                                             | Not supported   |                                                                                                        |
| M:System.Type.IsAssignableFrom(System.Type)                                                                                                             | Not supported   |                                                                                                        |
| M:System.Type.IsSubclassOf(System.Type)                                                                                                                 | Supported: 2.0+ | .GetTypeInfo().IsSubclassOf.                                                                           |
| M:System.Reflection.MemberInfo.get_ReflectedType                                                                                                        | Supported: 2.0+ | Remove usage: As CAS is not supported in newer frameworks, this property no longer has meaning.        |
| M:System.Activator.CreateInstance(System.Type,System.Reflection.BindingFlags,System.Reflection.Binder,System.Object[],System.Globalization.CultureInfo) | Supported: 2.0+ |                                                                                                        |

**Comment by jogibear9988** [comment]
Any News to this?

**Comment by joelweiss** [comment]
Worked on it a while back [here](/joelweiss/ChangeTracking/tree/netstandard), as far as I can recall the only issue with running the tests.
Will try to take another look at it this week

**Comment by jogibear9988** [comment]
thx

**Comment by joelweiss** [comment]
Check out [2.0.0-Beta](https://www.nuget.org/packages/ChangeTracking/2.0.0-Beta).
