### ISSUE TITLE
PCL

### ISSUE THREAD

**Issue by weitzhandler** [joelweiss/ChangeTracking#23]
Hi,

I'm trying to add the nuget package to my Xamarin PCL (profile 44), and I get the following error:
>Could not install package 'Castle.Core 3.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Anyway to make it work?

**Comment by joelweiss** [comment]
Not as far as I know. since Castle.Core does not support PCL. castleproject/Core#41
