### ISSUE TITLE
ListView in Xamarin.Forms doesn't refresh when the underlying collection is updated!

### ISSUE THREAD

**Issue by toumir** [joelweiss/ChangeTracking#29]
Hi,
```
public class MyOrder 
{
	public Order Order { get; set; }
	
	public MyOrder()
	{
		var _iniOrder = new Order(); 		//class that you use
		Order = _iniOrder.AsTrackable();
	}
}
```
**XAML:** 

```
<ListView ItemsSource="{Binding MyOrder.Order.OrderDetails}" .../>
```
**Adding item**

```
public MyOrder Mo { get;set; }
Mo = new MyOrder();
...
Mo.Order.OrderDetails.Insert(0, new OrderDetail
{
	ItemNo = Guid.NewGuid().ToString(),
	OrderDetailId = new Random().Next(1, 100)
});	
```
ListView does not refresh when the underlying collection is updated(ie: Mo.Order.OrderDetails): 

even the collection has data!

**FYI : The code above works fine in wpf but doesn't work for Xamarin.Forms(Android/UWP)!**

![xf-android](https://user-images.githubusercontent.com/10366325/37567033-45be918a-2ac1-11e8-839a-5170978c2bae.gif)

![wpf](https://user-images.githubusercontent.com/10366325/37567034-45ecdb44-2ac1-11e8-9878-7288d81e6a1c.gif)

is there an explanation? thanks in advance and thanks for sharing this!

**Comment by joelweiss** [comment]
Sorry but I have never used Xamarin Forms, I don't know how their Binding system works.

**Comment by toumir** [comment]
Thanks for your reply and for your time,
Binding system in XF is pretty much the same as WPF, any case what I'm doing now, is to use second collection (ObservableCollection<T>) and when changes occurs in the trackable collection, I update My collection,  it's annoying and duplicate code but it works for me, 
if anyone can help will be appreciated!
Thanks in advance

**Comment by toumir** [comment]
Hi @joelweiss , I wonder if there is any way/event to know if the collections(addedItems/removedItems/changedItems) has been changed, get notification when items added, removed or  changed ?
thanks again

**Comment by toumir** [comment]
got it
```
((IBindingList)MyCollection).ListChanged +=OnListChanged; 

private void OnListChanged(object sender, ListChangedEventArgs e)
        {
            if(e.ListChangedType == ListChangedType.ItemAdded)
            {
                //...
            }

            if (e.ListChangedType == ListChangedType.ItemChanged)
            {
                //...
            }

            if (e.ListChangedType == ListChangedType.ItemDeleted)
            {
                //...
            }
        }
```

**Comment by joelweiss** [comment]
Here is what the library essentially does in regards to change tracking

```csharp
public class Order: INotifyPropertyChanged 
{
	private int _Id;
	public virtual int Id
	{
		get => _Id;
		set
		{
			_Id = value;
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Id)));
		}
	}

	private string _CustumerNumber;
	public virtual string CustumerNumber
	{
		get => _CustumerNumber;
		set
		{
			_CustumerNumber = value;
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CustumerNumber)));
		}
	}
	private BindingList<OrderDetail> _OrderDetails;
	public virtual BindingList<OrderDetail> OrderDetails
	{
		get => _OrderDetails;
		set
		{
			if (_OrderDetails != null)
			{
				_OrderDetails.ListChanged -= OnListChange;
			}
			_OrderDetails = value;
			if (_OrderDetails != null)
			{
				_OrderDetails.ListChanged += OnListChange;
			}
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(OrderDetails)));
		}
	}

	void OnListChange(object sender, ListChangedEventArgs e) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(OrderDetails)));

	public event PropertyChangedEventHandler PropertyChanged;
}

public class OrderDetail : INotifyPropertyChanged 
{
	private int _OrderDetailId;
	public virtual int OrderDetailId
	{
		get => _OrderDetailId;
		set 
		{
			_OrderDetailId = value;
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(OrderDetailId)));
		}
	}
	
	private string _ItemNo;
	public virtual string ItemNo
	{
		get => _ItemNo;
		set
		{
			_ItemNo = value;
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(ItemNo)));
		}
	}
	public event PropertyChangedEventHandler PropertyChanged;
}
```

see if this works.

```chsarp
void Main()
{
	var Mo = new MyOrder();

	Mo.Order.OrderDetails.Insert(0, new OrderDetail
	{
		ItemNo = Guid.NewGuid().ToString(),
		OrderDetailId = new Random().Next(1, 100)
	});
}

public MyOrder Mo { get; set; }

public class MyOrder
{
	public Order Order { get; set; }

	public MyOrder()
	{
		Order = new Order();
		Order.OrderDetails = new BindingList<UserQuery.OrderDetail>();
	}
}
```

**Comment by toumir** [comment]
not working with BindingList<T>  but when I replaced BindingList<T> with ObservaleCollection<T> with some changes , **it works!,**
I think there is an issues between BindingList and XF, 
enable some option in VS IDE to get more debugging Information in the output window, I see that there
a problem!
I'm looking for solution in XF Forum, I'll be back
@joelweiss Thanks again for your time,

**Comment by toumir** [comment]
FYI : https://forums.xamarin.com/discussion/comment/143925#Comment_143925

**Comment by toumir** [comment]
unfortunately your library is not compatible with Xamarin Forms unless you use ObservableCollection instead of BindingList, I wonder if this is possible ? 
Thanks Sir!

**Comment by joelweiss** [comment]
What if you replace `BindingList<OrderDetail>` with `OrderDetailCollection` like so

```charp
...
private OrderDetailCollection _OrderDetails;
public virtual OrderDetailCollection OrderDetails
{
	get => _OrderDetails;
	set
	{
		if (_OrderDetails != null)
		{
			_OrderDetails.ListChanged -= OnListChange;
		}
		_OrderDetails = value;
		if (_OrderDetails != null)
		{
			_OrderDetails.ListChanged += OnListChange;
		}
		PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(OrderDetails)));
	}
}
...
public class OrderDetailCollection : BindingList<OrderDetail>, INotifyCollectionChanged
{

	protected override void OnListChanged(ListChangedEventArgs e)
	{
		base.OnListChanged(e);
		CollectionChanged?.Invoke(this, new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
	}
	public event NotifyCollectionChangedEventHandler CollectionChanged;
}
```
Does it fire properly?

**Comment by toumir** [comment]
Excellent! now it working
![itworking](https://user-images.githubusercontent.com/10366325/37638875-506a57c8-2c0f-11e8-8f9c-c7a1451a051f.gif)

we must implement INotifyCollectionChanged (like ObservableCollection Does), it allows the binding engine to update the UI when the list is updated.
The thing I did not understand is, why it works in WPF ?!

thanks Sir :) 👍

**Comment by toumir** [comment]
one more thing if you allow?
What about casting AsTrackable in this case?
Mo.Order.AsTrackable(),  Mo.Order.OrderDetails Collection Property should be Trackable, it throws an InvalidCastException!
thanks

**Comment by joelweiss** [comment]
I did not make any changes to the code, we were just investigating why the change notification did not work in xamarin forms and how we can make it work. 
The `OrderDetailCollection` implements only the change notification part not the change tracking.

**Comment by toumir** [comment]
it is possible to add INotifyCollectionChanged ?

**Comment by joelweiss** [comment]
Please test with [Nuget Version 2.0.5-Beta](https://www.nuget.org/packages/ChangeTracking/2.0.5-Beta) and let me know.

**Comment by toumir** [comment]
Hi @joelweiss 
after testing I get this : 

1- The binding work as **expected** 👍  , but the casting to get the trackable information not, I get an invalid cast exception **System.InvalidCastException: Specified cast is not valid.**
```
var Mo = new MyOrder();
Mo.Order.OrderDetails.CastToIChangeTrackableCollection(); //<=== OrderDetails is now of type ObservableCollection
```

I added the appropriate extension method but still not working :
```
public static class Extensions
    {
        public static IChangeTrackableCollection<T> CastToIChangeTrackableCollection<T>(this ObservableCollection<T> target) where T : class
        {
            return (IChangeTrackableCollection<T>)target;
        }
    } 
```

2- Using the test project, I **change** the OrderDetails Property from List<T> to **ObservableCollection<T>** and run the tests: tests passes exception one: 

```
[Fact]
        public void When_CollectionProperty_Children_Not_Trackable_Change_CollectionProperty_Should_Not_Raise_PropertyChanged_Event()
        {
}
```
thanks Sir.

**Comment by joelweiss** [comment]
Hi,

I don't understand what still not working, this work fine
```csharp
    Order order = new Order();
    var trackable = order.AsTrackable();	
    trackable.OrderDetails.CastToIChangeTrackableCollection();
```
If the issue of change notification is fixed, lets close this issue, and please open a new issue for any other issues.

**Comment by toumir** [comment]
yes the issue of change notification is fixed

**Comment by joelweiss** [comment]
@toumir Thanks for helping me figure out this issue, for any outstanding issues please open a new issue.
