### ISSUE TITLE
InvalidCastException when using ObservableCollection

### ISSUE THREAD

**Issue by toumir** [joelweiss/ChangeTracking#31]
Change the OrderDetails type to ObservableCollection<T>
```
public class Order
{
...
public Order()
{
   OrderDetails = new ObservableCollection<OrderDetail>();
}
...
public virtual ObservableCollection<OrderDetail> OrderDetails { get; set; }
...
}
```
Order order = new Order();
var trackable = order.AsTrackable();
trackable.OrderDetails.CastToIChangeTrackableCollection(); //Invalid cast exception

**InvalidCastException: Unable to cast object of type 'System.Collections.ObjectModel.ObservableCollection`1[UserQuery+OrderDetail]' to type 'ChangeTracking.IChangeTrackableCollection`1[UserQuery+OrderDetail]'.**

what I'm missing ? 
thanks Sir.

**Comment by joelweiss** [comment]
See in [Readme](https://github.com/joelweiss/ChangeTracking#for-collections)

> You can only assign the created proxy to one of the implemented interfaces, i.e. `ICollection<T>`, `IList<T>` and `IBindingList`, and the `AsTrackable<T>()` will choose the correct extennsion method only if called on `IList<T>`, `IList`, `ICollection<T>` and `ICollection`.

I guess I should add that the same applies to Collection Properties.

the following whould work.

```csharp
void Main()
{
    Order order = new Order();
    var trackable = order.AsTrackable();
    trackable.OrderDetails.CastToIChangeTrackableCollection();
}


public class Order
{
    public Order()
    {
        OrderDetails = new ObservableCollection<OrderDetail>();
    }

    public virtual IList<OrderDetail> OrderDetails { get; set; }
}

public class OrderDetail
{
    public virtual int OrderDetailId { get; set; }
    public virtual string ItemNo { get; set; }
}

```

But why do you want to use `ObservableCollection<T>`?
