### ISSUE TITLE
Get modified properties on an object?

### ISSUE THREAD

**Issue by monodop** [joelweiss/ChangeTracking#32]
I'm having a hard time getting the list of properties that were changed on a tracked object. Is this possible with the current API, or do I just have to manually get the properties again myself, iterate over the object, and compare the current values to the original values? Perhaps this would be a nice thing to add to the API?

My use case for this is that I would like to apply a series of transformations to a complex object, then boil that down to what objects/properties/lists have been added, removed, and modified, so I can pass that simplified diff to another component in my program.

Thanks for the hard work!
 \- Harrison

**Comment by joelweiss** [comment]
> Is this possible with the current API

It is now... 😄 

Try out the latest version ([Nuget](https://www.nuget.org/packages/ChangeTracking/2.0.10-Beta)) and let me know.

```csharp
//If ChangeTrackingStatus is Changed it returns all changed property names, if ChangeTrackingStatus is Added or Deleted it returns all properties
trackable.ChangedProperties();
```

**Comment by monodop** [comment]
Excellent, thanks!

I noticed it's going into a beta pre-release. Any idea when version 2.0 will be released?

**Comment by joelweiss** [comment]
Just released.
