### ISSUE TITLE
How to get the underlying entity object from entity proxy at runtime 

### ISSUE THREAD

**Issue by toumir** [joelweiss/ChangeTracking#35]
How to get the underlying entity object from entity proxy at run time without the extra code added by proxy

**pseudocode :** 
```
Order trackedOrder = order.AsTrackable();
//... do  something with trackedOrder
//..
//hard to serialize trackedOrder
```
**what I want :** 
```
//getting the changed object without extra code 
var order_without_extra_code =  trackedOrder.GetUnderlyingObject() 

Serialize(order_without_extra_code)

```
The **cast to the base type** (Order) not working for me, still get the extra code: 
```
Order order = (Ordre)trackedOrder;//not working
```

can you help ? 
thanks in advance

**Comment by toumir** [comment]
using **AutoMapper** fix my problems
```
//create map
cfg.CreateMap<Order, Order>();

var order_without_extra_code = Mapper.Map<Order, Order>(trackedOrder);

// I can serialize or save the object without problems
Serialize(order_without_extra_code) 
```

what do you think ?

**Comment by joelweiss** [comment]
That's what I suggested [here](https://github.com/joelweiss/ChangeTracking/issues/16#issuecomment-271224375)
Given that you are not the first one who asks for this feature, I will add it soon.
