### ISSUE TITLE
Not allowing primatives in a collection is a pain point

### ISSUE THREAD

**Issue by Codehulk** [joelweiss/ChangeTracking#4]
Something like this would be valuable.
           
    IList<string> fooList = new List<string>();
    IList<string> trackableFooList = fooList.AsTrackable();
    trackableFooList.Add("Hi");
    var trackable = trackableFooList.CastToIChangeTrackableCollection();

    foreach (var addedItem in trackable.AddedItems)
    {
        Console.WriteLine("ADDED: " + addedItem);
    }

    Console.ReadKey();

**Comment by joelweiss** [comment]
As `AddedItems` I can give you the primitives that were not in the list when starting to track (or `SaveChanges()` is called), and as `DeletedItems` the primitives that were deleted.
But how do you propose we handle changed items?
And what happens if you change "Foo"  to "Bar" (`trackableFooList[0] = "Bar"`) and then add back "Foo" again?

**Comment by Codehulk** [comment]
Primitives are immutable so I guess I wouldn't expected any changes.  Just adds and removes.  But if we really wanted change tracking I guess one strategy would be anytime the collection would be modified out side of an explicity "Add", "Remove" so for example:

    trackableFooList[0] = "Bar";

Their could be snapshot level tracking based on index.

**Comment by joelweiss** [comment]
I don't think I want to automatically wrap primitive values (or any value or Immutable Type for that matter), here is how I would go about it, and maybe down the road if I feel its a common use case I will add it in.

```csharp
public class PrimativeWrapper<T>
{
	public PrimativeWrapper() { }
	public PrimativeWrapper(T primative)
	{
		Primative = primative;
	}

	public virtual T Primative { get; set; }
}
public static class PrimativeWrapperExtensions
{
	public static IEnumerable<PrimativeWrapper<T>> WrapPrimatives<T>(this IEnumerable<T> enumerable)
	{
		if (enumerable == null)
		{
			throw new ArgumentNullException(nameof(enumerable));
		}
		return WrapPrimativesImpl<T>(enumerable);
	}

	private static IEnumerable<PrimativeWrapper<T>> WrapPrimativesImpl<T>(IEnumerable<T> enumerable)
	{
		foreach (var item in enumerable)
		{
			yield return new PrimativeWrapper<T>(item);
		}
	}
}
```

and use it like this.
```csharp
var list = new List<int> { 1, 2, 3, 4 };
var wrappedList = list.WrapPrimatives().ToList();
var tracked = wrappedList.AsTrackable();

tracked.First().Primative = 2;
```

**Comment by jlopez788** [comment]
I implemented a dynamic comparer at work, what I used was a key getter for poco class or if it was a primitive I used the index as key and tracked changes that way.
