### ISSUE TITLE
IComplexPropertyTrackable is internal

### ISSUE THREAD

**Issue by PatrikTrestik** [joelweiss/ChangeTracking#41]
I want to construct a hierarchy of changes. If IComplexPropertyTrackable would be accessible it is easy to traverse hierarchy down through IChangeTrackables.

I don't suggest to build-in change hierarchy function, because it is more complex. There could be circular references and so on.
In my specific case, I know how tracked objects look like and could safely traverse hierarchy.

The same case is ICollectionPropertyTrackable if I can traverse collections.

**Comment by joelweiss** [comment]
I don't understand what you are trying to achieve, can you give an example?

**Comment by PatrikTrestik** [comment]
I'm sorry that I'm a little overloaded in work. I'll try to provide the working example later.

Here is short story:

`//Only pseudocode
class ComplexObject 
{
  public virtual string SimpleProp {get;set;}
  public virtual ChildObject ObjectProp {get;set;} = new ChildObject();
}

var obj=(new ComplexObject()).AsTrackable();
obj.SimpleProp="Test";
obj.ObjectProp.SimpleChildProp = "Test Child";
obj.ChangedProperties  // Will return ["SimpleProp"] - by definition correct
obj.ChildObject is IChangeTrackable //Great, it is as I expected
obj.ChildObject.ChangedProperties //If I have knowledge of object it is no problem to traverse hierarchy 
//If I write generic repository, I have no knowledge of object structure
anyObj = obj as IChangeTrackable;
anyObj.ChangedPropeties //Happy here

(anyObj as IComplexPropertyTrackable).ComplexPropertyTrackables  //**This will help to go deeper**

`

Actually, I have repository using reflection to access  IComplexPropertyTrackable and it works well.

**Comment by joelweiss** [comment]
I have no current plans to make `IComplexPropertyTrackable` public api.
Like you said reflection is the way to go, here is an example

```csharp
void Main()
{
    var value = new ComplexObject().AsTrackable();
    value.SimpleProp = "Test1";
    value.ComplexObjectLevel1.SimpleProp = "Test2";
    value.ComplexObjectLevel1.ComplexObjectLevel2.ComplexObjectLevel3.SimpleProp = "Test3";
    DumpChanges(value, path: null);
}


public void DumpChanges(object value, string path)
{
    if (value is IChangeTrackable trackable)
    {
        HashSet<string> changedProperties = new HashSet<string>(trackable.ChangedProperties);
        foreach (PropertyInfo property in trackable.GetType().GetProperties())
        {
            object propertyValue = property.GetValue(trackable, null);
            if (changedProperties.Contains(property.Name) || propertyValue?.GetType().GetInterface(nameof(IChangeTrackable)) != null)
            {
                DumpChanges(propertyValue, $"{path}{(path == null ? null : ".")}{property.Name}");
            }
        }
    }
    else
    {
        Console.WriteLine($"{path}: {value}");
    }
}

public class ComplexObject
{
    public virtual string SimpleProp { get; set; }
    public virtual ComplexObjectLevel1 ComplexObjectLevel1 { get; set; } = new ComplexObjectLevel1();
}

public class ComplexObjectLevel1
{
    public virtual string SimpleProp { get; set; }
    public virtual ComplexObjectLevel2 ComplexObjectLevel2 { get; set; } = new ComplexObjectLevel2();
}

public class ComplexObjectLevel2
{
    public virtual string SimpleProp { get; set; }
    public virtual ComplexObjectLevel3 ComplexObjectLevel3 { get; set; } = new ComplexObjectLevel3();
}

public class ComplexObjectLevel3
{
    public virtual string SimpleProp { get; set; }
}
```

will output

>`SimpleProp: Test1`
>`ComplexObjectLevel1.SimpleProp: Test2`
>`ComplexObjectLevel1.ComplexObjectLevel2.ComplexObjectLevel3.SimpleProp: Test3`

HTH

**Comment by PatrikTrestik** [comment]
I have ChangeHierarchy method in my project using reflection. My problem is well solved now.

Once I'll have some spare time, I'll post a pull request with such method realized with internals. You can then decide if it could be any use for the project.
