### ISSUE TITLE
CollectionChanged not firing when Inserting Items to Trackable Collection!!!

### ISSUE THREAD

**Issue by toumir** [joelweiss/ChangeTracking#43]
var order = new Order
	{
		Id = 1,
		CustomerNumber = "Test",
		Address = new Address
		{
			AddressId = 1,
			City = "New York"
		},
		OrderDetails = new ObservableCollection<OrderDetail>
		{
			new OrderDetail
			{
				OrderDetailId = 1,
				ItemNo = "Item123"
			},
			new OrderDetail
			{
				OrderDetailId = 2,
				ItemNo = "Item369"
			}
		}
	};

	TrackableOrder = order.AsTrackable();

	((INotifyCollectionChanged)TrackableOrder.OrderDetails).CollectionChanged += OnCollectionChanged;
	
	private void OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
    {
        //called on add but not On Insert
    }
	

**Adding items with Insert OnCollectionChanged never called thus the UI will not be notified** 
	
	TrackableOrder.OrderDetails.Insert(0, new OrderDetail()
	{
	    ItemNo = $"{Guid.NewGuid()}",
	    OrderDetailId = 100
	});

**Adding items with Add OnCollectionChanged called** 
	
	TrackableOrder.OrderDetails.Add(new OrderDetail()
	{
		ItemNo = $"{Guid.NewGuid()}",
		OrderDetailId = 200
	});
	
	
Can you confirm this Sir @joelweiss ?

**Comment by joelweiss** [comment]
@toumir Thanks for the thorough reproduction steps.

this is fixed in #44 
please take the latest version from [nuget ](https://www.nuget.org/packages/ChangeTracking/2.0.20)and let me know.

**Comment by toumir** [comment]
@joelweiss perfect it works now thank you Sir :)
