### ISSUE TITLE
Complex Properties with Read-Only Properties

### ISSUE THREAD

**Issue by elowareKf** [joelweiss/ChangeTracking#47]
Tracking a class with a complex property does not work if the complex property has a read only property by itself. Here is the Code for this:

        public class TestSubClass {
            public virtual string Name { get; set; }

            // Adding the following Line causes an error by tracking the SubClass
            public virtual double SomeWhat => 10.5f;

            public override string ToString() => Name;

        }

        public class ErrorClass {
            public virtual TestSubClass Test { get; set; }
            public ErrorClass()  {
                Test = new TestSubClass();
            }
        }

        [TestMethod]
        public void CauseError() {
            var error = new ErrorClass().AsTrackable();
            error.Test.Name = "Changed it";
            Assert.IsTrue(error.CastToIChangeTrackable().IsChanged, "ChangeTracking for SubClass failed");

        }

You can also just add the line:
 public virtual string Zip => "12345";

Into the Address class of the ChangeTracking.Tests Project

**Comment by joelweiss** [comment]
Thanks for the detailed report.
I fixed this behavior, please try the latest version [2.1.0](https://www.nuget.org/packages/ChangeTracking/2.1.0)
