### ISSUE TITLE
Get underlying entity object without trackable

### ISSUE THREAD

**Issue by Int32Overflow** [joelweiss/ChangeTracking#48]
How can I get underlying object without trackable proxy interface?

**Comment by toumir** [comment]
Hi @Int32Overflow 

[https://github.com/joelweiss/ChangeTracking/pull/37](url)

        [Fact]
        public void GetCurrent_Should_Return_Original()
        {
            var order = Helper.GetOrder();
            var trackable = order.AsTrackable();

            trackable.Id = 124;
            trackable.CustomerNumber = "Test1";

            var current = trackable.CastToIChangeTrackable().GetCurrent();

            current.ShouldBeEquivalentTo(trackable);
            (current is IChangeTrackable).Should().BeFalse();
        }

**Comment by Int32Overflow** [comment]
Thank you
