### ISSUE TITLE
Cost much more memory

### ISSUE THREAD

**Issue by dongshengfengniaowu** [joelweiss/ChangeTracking#49]
33328 Tracking  objects will create 33328 Proxy , Costed much more memory .How about use Singleton mode ?
![image](https://user-images.githubusercontent.com/39110620/61275858-65dd6880-a7e1-11e9-9c2f-b0a0acba8c1d.png)

**Comment by joelweiss** [comment]
I don't see anything in the image.

**Comment by joelweiss** [comment]
Closed do to missing info.
