### ISSUE TITLE
Receive exception "Property et is not virtual.  Can't track class with non-virtual properties"

### ISSUE THREAD

**Issue by Codehulk** [joelweiss/ChangeTracking#5]
There is now "et" property on PetOwner so I think it must be truncating Pets or something.  I ran into this problem before I believe when I didn't have a default constructor.  I'm not sure what is causing this one.

The exception occurs on the following line 

    var trackablePetOwner = petOwner.AsTrackable();

Here is the full code

    public class PetOwner
    {
        public virtual IList<Pet> Pets { get; private set; }

        public PetOwner()
        {
            Pets = new List<Pet>();
        }

        public void AddPet(string name)
        {
            Pets.Add(new Pet {Name = name});
        }
    }

    public class Pet
    {
        public virtual string Name{ get; set; }
    }    

    class Program
    {
        static void Main(string[] args)
        {
            var petOwner = new PetOwner();
            var trackablePetOwner = petOwner.AsTrackable();

            trackablePetOwner.AddPet("Fido");

            foreach (var pet in trackablePetOwner.Pets.CastToIChangeTrackableCollection().AddedItems)
            {
                Console.WriteLine("Added: " + pet.Name);
            }

            Console.WriteLine("Done...");
            Console.ReadKey();

        }
    }

**Comment by Codehulk** [comment]
Problem seems to be all method calls must be declared as virtual as well.

**Comment by joelweiss** [comment]
Fixed
