### ISSUE TITLE
Is it possible to track previous changes?

### ISSUE THREAD

**Issue by mattbrailsford** [joelweiss/ChangeTracking#50]
Hey, just wondering, is it possible to remember what was changed for the last AcceptChanges call? My use case would be to fire a post save event and be able to know what was changed in the last commit.

**Comment by joelweiss** [comment]
I am not sure I understand your scenario.
Before Calling `Accept Changes()` you can get which properties are changed via
```csharp
//If ChangeTrackingStatus is Changed it returns all changed property names, if ChangeTrackingStatus is Added or Deleted it returns all properties
trackable.ChangedProperties();
```

Is that what you are asking?

**Comment by mattbrailsford** [comment]
Sorry, it was more if there was or could be a way post `AcceptChanges()` to access something like 'trackable.PreviousProperties()` to know what the previous state of the object was.

**Comment by joelweiss** [comment]
No, there is no way.

but you can call `trackable.GetCurrent()` before calling `AcceptChanges()` and then compare the differences. HTH

**Comment by mattbrailsford** [comment]
Cool. I'll have a play and see what I come up with. Thanks for the suggestion 👍
