### ISSUE TITLE
DoNoTrackAttribute is inaccessible due to its protection level

### ISSUE THREAD

**Issue by isaacqc** [joelweiss/ChangeTracking#58]
It says "DoNoTrackAttribute is inaccessible due to its protection level" whenever I try to use DoNoTrack attribute for my model properties in my project. 

And I found out "internal sealed class DoNoTrackAttribute : Attribute", DoNoTrackAttribute is not public. Should it be public instead?

**Comment by joelweiss** [comment]
@isaacqc 
Yep, you are correct, will have a new release soon.

**Comment by joelweiss** [comment]
@isaacqc 
I Just released [2.2.17](https://www.nuget.org/packages/ChangeTracking/2.2.17) to nuget, Let me know if you have any more issues.

**Comment by isaacqc** [comment]
Thanks for the prompt response! I will try it asap

**Comment by isaacqc** [comment]
It works. Thanks a lot!
