### ISSUE TITLE
Items added to trackable collections from withing the proxy don't register in added/removed/changed items

### ISSUE THREAD

**Issue by Codehulk** [joelweiss/ChangeTracking#6]
This is a big one for us as we are doing DDD and a lot of the interactions with the object would be from inside the object itself.

See the following code.  I would expect the output to be 
Added: Fido
Added: Fluffy

But all that shows is
Added: Fluffy

  public class PetOwner
    {
        public virtual IList<Pet> Pets { get; private set; }

        public PetOwner()
        {
            Pets = new List<Pet>();
        }

        public virtual void AddPet(string name)
        {
            Pets.Add(new Pet {Name = name});
        }
    }

    public class Pet
    {
        public virtual string Name{ get; set; }
    }    

    class Program
    {
        static void Main(string[] args)
        {
            var petOwner = new PetOwner();
            var trackablePetOwner = petOwner.AsTrackable();

            
            // !!! Fido DOES NOT appear in AddedItems !!!
            trackablePetOwner.AddPet("Fido");

            // !!! Fluffy shows as added in the AddedItems collection !!!
            trackablePetOwner.Pets.Add(new Pet { Name = "Fluffy" });

            foreach (var pet in trackablePetOwner.Pets.CastToIChangeTrackableCollection().AddedItems)
            {
                Console.WriteLine("Added: " + pet.Name);
            }

            Console.WriteLine("Done...");
            Console.ReadKey();

        }
    }

**Comment by joelweiss** [comment]
I'm afraid this is not possible because there is no way for me to intercept anything you do on the target (original) list.
In fact the only reason this doesn't throw an exception is because of an optimization in the code, that if you make objects trackable the properties won't get trackable until first use, meaning the following will :boom:
```csharp
...
var petOwner = new PetOwner();
var trackablePetOwner = petOwner.AsTrackable();

var v = trackablePetOwner.Pets;

// !!! Can't do nothing about it, I don't even know that it happened !!!
trackablePetOwner.AddPet("Fido");

/// throws "Unable to cast object of type 'Test.Pet' to type 'ChangeTracking.IChangeTrackable`1[Test.Pet]'."
foreach (var pet in trackablePetOwner.Pets.CastToIChangeTrackableCollection().AddedItems)
{
    Console.WriteLine("Added: " + pet.Name);
}
...
```
I don't know the DDD patern, but will this fit your workflow?
```csharp
public class PetOwner
{
    public virtual IList<Pet> Pets { get; private set; }
    public virtual string OwnerName { get; set; }
    public PetOwner(IList<Pet> pets)
    {
        Pets = pets;
    }

    // Needed for proxy
    // [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public PetOwner()
    {
    }

    public void AddPet(string name)
    {
        Pets.Add(new Pet { Name = name });
    }
}

public class Pet
{
    public virtual string Name { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        var petOwner = new PetOwner(new List<Pet>().AsTrackable());

        // !!! Fido shows as added in the AddedItems collection !!!
        petOwner.AddPet("Fido");

        // !!! Fluffy shows as added in the AddedItems collection !!!
        petOwner.Pets.Add(new Pet { Name = "Fluffy" });

        foreach (var pet in petOwner.Pets.CastToIChangeTrackableCollection().AddedItems)
        {
            Console.WriteLine("Added: " + pet.Name);
        }

        //and if you wish you can turn the whole thing into a trackable
        var trackable = petOwner.AsTrackable();
        trackable.CastToIChangeTrackable().AcceptChanges();
        int count = petOwner.Pets.CastToIChangeTrackableCollection().AddedItems.Count();
        Console.WriteLine("Added Items count {0}", count);

        Console.WriteLine("Done...");
        Console.ReadKey();
    }
}
```

**Comment by Codehulk** [comment]
I think we can make this work.  All object construction will be handled elsewhere.  With DDD, one of the goals would be to push all the non business concerns out of the mind of the consumer of the business models.  So if we go this route I think we could possibly wrap all object construction in a factory or something.
