### ISSUE TITLE
Access to sourcecollection

### ISSUE THREAD

**Issue by schhwork** [joelweiss/ChangeTracking#65]
Hi,

Im changetracking an ObservableCollection and depend on the Move method, but i cant see a way to access the originalcollection so i can do a move. Is there a way to get the proxy as the Original IList so i can cast and do the move.

Thank you

**Comment by joelweiss** [comment]
You can not access the original `ObservableCollection`.

The current implementation does not support removing and adding back a trackable to the collection.
Depending on your scenario the following might work, however the moved item will be considered added unless you call `AcceptChanges()`
```csharp
void Main()
{
	IList<Foo> observableCollection = new ObservableCollection<Foo>
	{
		new Foo { Id = 0 },
		new Foo { Id = 1 },
		new Foo { Id = 2 },
		new Foo { Id = 3 }
	};
	IList<Foo> trackableCollection = observableCollection.AsTrackable();
	
	var itemToMove = trackableCollection[1].CastToIChangeTrackable().GetCurrent();
	trackableCollection.RemoveAt(1);
	trackableCollection.Insert(3, itemToMove);
	trackableCollection[3].CastToIChangeTrackable().AcceptChanges();
}

public class Foo
{
	public virtual int Id { get; set; }
}
```
Hope this helps

**Comment by schhwork** [comment]
I was hoping there was some built in way but doing my own move like above works well enough, i appreaciate the quick response.
