### ISSUE TITLE
How do I get an object which is already a trackable to get the status deleted?

### ISSUE THREAD

**Issue by martijnburgers** [joelweiss/ChangeTracking#67]
[Fact]
        public void DeletedTest()
        {
            SomeEntity entity = new SomeEntity();

            entity = entity.AsTrackable();

            //how do i now get the status to deleted? The object was already set as trackable elsewhere
        }

Do I need to unwrap it first and make it trackable again with providing the Deleted status?

**Comment by joelweiss** [comment]
There is currently no support to change the `ChangeTrackingStatus` directly, the only way it gets deleted is when removed from a trackable collection.

HTH
