### ISSUE TITLE
List(Of).AsTrackable()

### ISSUE THREAD

**Issue by iblade-dev** [joelweiss/ChangeTracking#69]
Hi,

Can this be fixed, or I always need to declare with:
xToolModulesL = (New List(Of cTool_Module)).AsTrackable(makeComplexPropertiesTrackable:=True, makeCollectionPropertiesTrackable:=True)

![image](https://user-images.githubusercontent.com/78237299/106332671-8c5dda00-6287-11eb-845a-3a25d39cbfc8.png)

Thanks.

**Comment by joelweiss** [comment]
I am not familiar with VB overload resolution.

What might work is if you can create a helper extension method that calls it with the `makeComplexPropertiesTrackable:=True, makeCollectionPropertiesTrackable:=True` filled out, so wont have to type it everytime.
