### ISSUE TITLE
Bug add item to collection

### ISSUE THREAD

**Issue by TTD-TranNam** [joelweiss/ChangeTracking#83]
Dear team, when I add a new item to List then exception was throw, how can I handle this?
![image](https://github.com/joelweiss/ChangeTracking/assets/100107230/f78a2494-bd3c-49f4-8ec6-f99514a9b52c)

**Comment by joelweiss** [comment]
without a reproduction example it is hard to answer, but my guess is that your trying to add to the original collection not the new trackable collection.
